apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-lms-backend
spec:
  selector:
    matchLabels:
      app: lms-backend
  template:
    metadata:
      labels:
        app: lms-backend
    spec:
      containers:
      - name: lms-backend
        image: "surendergupta/sparrow_backend:2"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: PORT

          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: MONGO_URL

          - name: JWT_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: JWT_TOKEN_SECRET

          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: AWS_REGION

          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: AWS_ACCESS_KEY_ID

          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: AWS_SECRET_ACCESS_KEY

          - name: AWS_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: AWS_BUCKET_NAME

          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: GITHUB_CLIENT_ID

          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: GITHUB_CLIENT_SECRET

          - name: COMPILER_URL
            value: "https://comiler.cloudcrypto.in"

        ports:
        - containerPort: 3000
